### ISSUE TITLE
Pages with custom extensions

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/mdsvex#1]
You can't use `.svx` or `.md` (in addition to any other custom extension) for routes.

**Comment by babichjacob** [comment]
The workaround, as demonstrated by the files added by the preset, is to mark it as hidden (`_whatever.md`) and import that in the `route-name.svelte` file and use the component there.

**Comment by dikaio** [comment]
Hi @babichjacob I was giving your svelte-add mdsvex a roll when I came across this issue. I know in sapper and svelte you can use `.md` `.svx` extensions as an endpoint has something changed in sveltekit that doesn't allow for this or it's just not implemented at this time?

Thanks bud! These svelte-adders `tailwind/graphql` are killer btw, thanks for building these out 👍🏻

**Comment by babichjacob** [comment]
> Hi @babichjacob I was giving your svelte-add mdsvex a roll when I came across this issue. I know in sapper and svelte you can use `.md` `.svx` extensions as an endpoint has something changed in sveltekit that doesn't allow for this or it's just not implemented at this time?
> 
> Thanks bud! These svelte-adders `tailwind/graphql` are killer btw, thanks for building these for the community 👍🏻

@dikaio Hi, thank you! There's a comment in the SvelteKit source code that they haven't implemented custom extensions for routes/pages and it's on the to do list.

**Comment by dikaio** [comment]
Ahh sweet I hadn't noticed that, I'm going to keep this installed I hear sveltekit is right around the corner 🥳 .

Again, thanks so much for this addition, appreciate what you're doing here.

**Comment by babichjacob** [comment]
Merging with #3
